version: '3.9'

services:
  flask_app:
    container_name: flask_app
    image: flask_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    ports:
      - "4000:4000"
    environment:
      DB_URL: postgresql://postgres:postgres@flask_db:5432/postgres
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      SERPAPI_API_KEY: ${SERPAPI_API_KEY}
    depends_on:
      - flask_db

  flask_db:
    container_name: flask_db
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: {}